[theme]
primaryColor = "#1cb3e0"
backgroundColor = "#222f3b"
secondaryBackgroundColor = "#344758"
textColor = "#d2d2d6"
font = "sans serif"

[server]
headless = true
maxUploadSize = 10

[browser]
gatherUsageStats = false
